-------------------------------------------------------------------------------
Test set: runner.TestRunner
-------------------------------------------------------------------------------
Tests run: 8, Failures: 2, Errors: 0, Skipped: 5, Time elapsed: 0.163 sec <<< FAILURE! - in runner.TestRunner
When I go to the application(Scenario: As a valid user I should be able to login to the application)  Time elapsed: 0.004 sec  <<< FAILURE!
java.lang.AssertionError: null
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertTrue(Assert.java:52)
	at stepDefinition.LoginTest.i_go_to_the_application(LoginTest.java:19)
	at ?.When I go to the application(feature/login.feature:6)

Scenario: As a valid user I should be able to login to the application  Time elapsed: 0.004 sec  <<< FAILURE!
java.lang.AssertionError: null
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertTrue(Assert.java:52)
	at stepDefinition.LoginTest.i_go_to_the_application(LoginTest.java:19)
	at ?.When I go to the application(feature/login.feature:6)

